### ISSUE TITLE
Pybadge error compiling example sketch micro_speech_arcarda

### ISSUE THREAD

**Issue by sgroombr** [adafruit/Adafruit_TFLite#4]
System information
Windows 10 laptop

TensorFlow installed from (source or binary): Both Arduino_TensorflowLite 2.1.0-ALPHA and Adafruit Tensorflow Lite 1.2.1 fronm the Arduino IDE libraries
Tensorflow version (commit SHA if source): dont know
Target platform (e.g. Arm Mbed OS, Arduino Nano 33 etc.): Pybadge M4 with external microphone
Describe the problem
got the following compile error:
Arduino: 1.8.13 (Windows 10), Board: "Adafruit pyBadge M4 Express (SAMD51), Enabled, 180 MHz (overclock), Fastest (-Ofast), 50 MHz (standard), TinyUSB, Off"
Multiple libraries were found for "Adafruit_ZeroDMA.h"
Used: C:\Users\Joanna\AppData\Local\Arduino15\packages\adafruit\hardware\samd\1.6.2\libraries\Adafruit_ZeroDMA
In file included from C:\Users\Joanna\Documents\Arduino\libraries\Adafruit_TensorFlow_Lite\examples\micro_speech_arcada\micro_speech_arcada.ino:22:
Not used: C:\Users\Joanna\Documents\Arduino\libraries\Adafruit_Zero_DMA_Library
audio_provider.h:19:10: fatal error: tensorflow/lite/c/c_api_internal.h: No such file or directory
19 | #include "tensorflow/lite/c/c_api_internal.h"
| ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
compilation terminated.
exit status 1
tensorflow/lite/c/c_api_internal.h: No such file or directory

Please provide the exact steps when you ran into the problem
Setup new Arduino IDE
Added Adafruit https://adafruit.github.io/arduino-board-index/package_adafruit_index.json
to boards manager url in preferences
Added Adafruit SAMD Boards 1.6.2
Added all Adafruit arcada libraries 2.5.0
Loaded Examples > Adafruit Tensorflow Lite > micro_speech_arcarda.

Got the attached error

**Comment by dhalbert** [comment]
Don't use the Arduino_TensorflowLite 2.1.0-ALPHA version right now; use the 1.15.0-ALPHA version. The 2.x version is not compatible with our existing code.

**Comment by ladyada** [comment]
fixed in latest commit, thanks :)
